on: #[push, pull_request, workflow_dispatch]
  workflow_dispatch:
  push:
    paths:
      - 'config/*.keymap'
      - 'config/*.yml'
      - 'boards/shields/forager/*.dtsi'
      - 'build.yaml'
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
